In [1]:
import torch

In [3]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)


tensor([[0.5565, 0.1442],
        [0.3275, 0.4961]])
tensor([[0.7192, 0.0033],
        [0.3463, 0.6491]])


In [10]:
x=torch.rand(5,3)
print(x)
print(x[1,1].item())



tensor([[0.7725, 0.6757, 0.9823],
        [0.3921, 0.9730, 0.0306],
        [0.7616, 0.1651, 0.0770],
        [0.4046, 0.6002, 0.4845],
        [0.5866, 0.6888, 0.0480]])
0.9730198979377747


In [18]:
x=torch.rand(4,4)
print(x)
y=x.view(-1,16)
print(y.size())


tensor([[0.9731, 0.1445, 0.9626, 0.1830],
        [0.0038, 0.4315, 0.0374, 0.4325],
        [0.0536, 0.8830, 0.5563, 0.8110],
        [0.3809, 0.4717, 0.8330, 0.0883]])
torch.Size([1, 16])


In [19]:
import numpy as np


In [21]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)


a+=1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
if torch.cuda.is_available():
    devivce=torch.device("cuda")
    x=torch.ones(5, device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y
    z=z.to("cpu")

In [26]:
x=torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [27]:
import torch

In [33]:
x=torch.rand(3, requires_grad=True)
print(x)
y=x+2
print(y)

z=y*y**2
print(z)

z=z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)

tensor([0.2673, 0.8358, 0.8933], requires_grad=True)
tensor([2.2673, 2.8358, 2.8933], grad_fn=<AddBackward0>)
tensor([11.6549, 22.8042, 24.2207], grad_fn=<MulBackward0>)
tensor(19.5599, grad_fn=<MeanBackward0>)
tensor([5.1405, 8.0416, 8.3713])


In [39]:
x=torch.rand(3, requires_grad=True)
print(x)
y=x+2
print(y)

z=y*y**2
print(z)

z=z.mean()
print(z)

#z.backward() #dz/dx
#print(x.grad)

v= torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward()
print(x.grad)

tensor([0.1282, 0.8943, 0.0735], requires_grad=True)
tensor([2.1282, 2.8943, 2.0735], grad_fn=<AddBackward0>)
tensor([ 9.6392, 24.2450,  8.9154], grad_fn=<MulBackward0>)
tensor(14.2665, grad_fn=<MeanBackward0>)
tensor([4.5293, 8.3769, 4.2996])


In [45]:
x=torch.rand(3, requires_grad=True)
print(x)

#x.require_grad_(False)
#x.detach()
#with torch.no_grad():

x.requires_grad_(False)
print(x)

x.detach()
print(x)

with torch.no_grad():
    y=x+2
    print(y)

tensor([0.6092, 0.2558, 0.6440], requires_grad=True)
tensor([0.6092, 0.2558, 0.6440])
tensor([0.6092, 0.2558, 0.6440])
tensor([2.6092, 2.2558, 2.6440])


In [50]:
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights=torch.ones(4, requires_grad=True)

optimizer=torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

In [ ]:
weights=torch.ones(4, requires_grad=True)

z.backward()

weights.grad.zero_()

In [54]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)

w=torch.tensor(1.0, requires_grad=True)

#forword pass and compute the loss
y_hat=w*x
loss=(y_hat-y)**2
print(loss)

#backward pass
loss.backward()
print(w.grad)

#update  weights
# next  weckwords

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [55]:
import numpy as np


In [77]:
X=torch.tensor([1,2,3,4], dtype=torch.float32)
Y=torch.tensor([2,4,6,8], dtype=torch.float32)

w=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

#model predictions
def forward(x):
    return w*x

#loss
def loss(y, y_predicted):
    return((y_predicted-y)**2).mean()

#gradient
#MSE = 1/N * (w*x - y)**2
#dJ/dw= 1/N 2x (w*x -y)


def gradient(x, y, y_predicted):
    return torch.dot(2*x, y_predicted-y).mean()
print(f'prediction before trainning:f(5)={forward(5):.3f}')

#trainning
learning_rate=0.01
n_iters=10

for epoch in range(n_iters):
    #prediction= forward pass
    y_pred=forward(x)

    #loss
    l=loss(Y, y_pred)

    #gradients=backward pass
    l.backward() #dl/dw

    #update weights
    with torch.no_grad():
        w-=learning_rate*w.grad

    #zero gradients
    w.grad.zero_()
    if epoch % 1==0:
        print(f'epoch {epoch+1}: w={w:.3f}, loss={l:.8f}')

print(f'prediction after trainning:f(5)={forward(5):.3f}')      

prediction before trainning:f(5)=0.000


RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [82]:
X=torch.tensor([1,2,3,4], dtype=torch.float32)
Y=torch.tensor([2,4,6,8], dtype=torch.float32)

w=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

#model predictions
def forward(x):
    return w * x


#loss
def loss(y, y_predicted):
    return((y_predicted-y)**2).mean()

#gradient
#MSE = 1/N * (w*x - y)**2
#dJ/dw= 1/N 2x (w*x -y)


def gradient(x, y, y_predicted):
    return torch.dot(2*x, y_predicted-y).mean()
print(f'prediction before trainning:f(5)={forward(5):.3f}')

#trainning
learning_rate=0.01
n_iters=10

for epoch in range(n_iters):
    #prediction= forward pass
    y_pred=forward(x)

    #loss
    l=loss(Y, y_pred)

    #gradients=backward pass
    l.backward() #dl/dw

    #update weights
    with torch.no_grad():
        w-=learning_rate*w.detach().numpy()

    #zero gradients
    w.grad.zero_()
    if epoch % 1==0:
        print(f'epoch {epoch+1}: w={w:.3f}, loss={l:.8f}')

print(f'prediction after trainning:f(5)={forward(5):.3f}')      

prediction before trainning:f(5)=0.000


RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [89]:
#1) Design model (input, output size, forward pass)
#2) construct loss and optimizer
#3) Trainning loop
#- forward pass: compute prediction
#- backward pass: gradients
# - update weights

import torch
import torch.nn as nn


X=torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y=torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)

X_test=torch.tensor([5], dtype=torch.float32)
n_samples, n_features=X.shape
print(n_samples, n_features)

input_size=n_features
output_size=n_features
model=nn.Linear(input_size,output_size)
    
print(f'prediction before trainning:f(5)={model(X_test).item():.3f}')

#gradient
#MSE = 1/N * (w*x - y)**2
#dJ/dw= 1/N 2x (w*x -y)


#def gradient(x, y, y_predicted):
 #   return torch.dot(2*x, y_predicted-y).mean()


#trainning
learning_rate=0.01
n_iters=100

#loss
loss=nn.MSELoss()
optimizer= torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_iters):
    #prediction= forward pass
    y_pred=model(x)

    #loss
    l=loss(Y, y_pred)

    #gradients=backward pass
    l.backward() #dl/dw

    #update weights
    optimizer.step()

    #zero gradients
    optimizer.zero_grad()
    if epoch % 1==0:
        [w,b]= model.parameters()
        print(f'epoch {epoch+1}: w={w[0][0].item():.3f}, loss={l:.8f}')

print(f'prediction after trainning:f(5)={model(X_test).item():.3f}')      

4 1
prediction before trainning:f(5)=3.583


TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [92]:
# 1) Design model (input, output, forward pass with different layers)
# 2) Construct loss and optimizer
# 3) Training loop
#       - Forward = compute prediction and loss
#       - Backward = compute gradients
#       - Update weights

import torch
import torch.nn as nn

# Linear regression
# f = w * x 

# here : f = 2 * x

# 0) Training samples, watch the shape!
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')
# 0) create a test sample
X_test = torch.tensor([5], dtype=torch.float32)

# 1) Design Model, the model has to implement the forward pass!
# Here we can use a built-in model from PyTorch
input_size = n_features
output_size = n_features

# we can call this model with samples X
model = nn.Linear(input_size, output_size)

'''
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        # define diferent layers
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)

model = LinearRegression(input_size, output_size)
'''

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

# 2) Define loss and optimizer
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 3) Training loop
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(X)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w, b] = model.parameters() # unpack parameters
        print('epoch ', epoch+1, ': w = ', w[0][0].item(), ' loss = ', l)

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

#samples: 4, #features: 1
Prediction before training: f(5) = 0.790
epoch  1 : w =  0.561310350894928  loss =  tensor(27.6783, grad_fn=<MseLossBackward0>)
epoch  11 : w =  1.7662389278411865  loss =  tensor(0.7161, grad_fn=<MseLossBackward0>)
epoch  21 : w =  1.9601197242736816  loss =  tensor(0.0185, grad_fn=<MseLossBackward0>)
epoch  31 : w =  1.9913727045059204  loss =  tensor(0.0005, grad_fn=<MseLossBackward0>)
epoch  41 : w =  1.9964649677276611  loss =  tensor(2.2024e-05, grad_fn=<MseLossBackward0>)
epoch  51 : w =  1.9973474740982056  loss =  tensor(9.3828e-06, grad_fn=<MseLossBackward0>)
epoch  61 : w =  1.9975509643554688  loss =  tensor(8.5433e-06, grad_fn=<MseLossBackward0>)
epoch  71 : w =  1.9976434707641602  loss =  tensor(8.0382e-06, grad_fn=<MseLossBackward0>)
epoch  81 : w =  1.9977163076400757  loss =  tensor(7.5701e-06, grad_fn=<MseLossBackward0>)
epoch  91 : w =  1.9977842569351196  loss =  tensor(7.1301e-06, grad_fn=<MseLossBackward0>)
Prediction after training: f(5

In [ ]:
  import torch
  import torch.nn as nn
  import numpy as np
  import sklearn import datasets
  import matplotlib.pyplot as plt

  x_numpy,